module ApplicationHelper

  # Returns the full title on a per-page basis.
   def full_title(page_title = '')
     base_title = "Default Title generated by Helper"
     if page_title.empty?
       base_title
     else
       "#{page_title} | #{base_title}"
     end
   end

   def string_shuffle(s)
     s.split('').shuffle
   end

end
